server:
    apiAiURL: http://httpbin.org/post
    apiAiKey: whocares
    baseConfigURL: src/main/resources
---
spring:
    profiles: dev
server:
    apiAiURL: http://httpbin.org/post
    apiAiKey: whocares
    baseConfigURL: src/main/resources
---
spring:
    profiles: prod
server:
    apiAiURL: http://httpbin.org/post
    apiAiKey: whocares
    baseConfigURL: src/main/resources